// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as View$RescriptReactStarter from "./View.bs.js";
import * as Model$RescriptReactStarter from "./Model.bs.js";

function App(Props) {
  return React.createElement(Model$RescriptReactStarter.make, {
              children: React.createElement(View$RescriptReactStarter.make, {})
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
