// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Model$RescriptReactStarter from "./Model.bs.js";

function View$TheHeader(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", {
                  className: "text-4xl font-bold text-gray-200"
                }, "New App"));
}

var TheHeader = {
  make: View$TheHeader
};

function View(Props) {
  var state = Model$RescriptReactStarter.State.use(undefined);
  var dispatch = Model$RescriptReactStarter.Dispatch.use(undefined);
  return React.createElement("div", {
              className: "flex flex-col items-center justify-center h-screen w-48 mx-auto"
            }, React.createElement(View$TheHeader, {}), React.createElement("div", {
                  className: "grid grid-cols-3 gap-4 mt-4 w-full"
                }, React.createElement("button", {
                      className: "p-4 py-1 rounded bg-red-500 text-red-900 hover:bg-red-400",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* Decrement */1);
                        })
                    }, "-"), React.createElement("div", {
                      className: "flex justify-center items-center"
                    }, state.count), React.createElement("button", {
                      className: "p-4 py-1 rounded bg-green-500 text-green-900 hover:bg-green-400",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* Increment */0);
                        })
                    }, "+")), React.createElement("button", {
                  className: "p-4 py-1 uppercase font-bold mt-2 w-full rounded bg-gray-500 text-gray-900 hover:bg-gray-400",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Reset */2);
                    })
                }, "Reset"));
}

var make = View;

export {
  TheHeader ,
  make ,
  
}
/* react Not a pure module */
